"""add_system_settings_and_user_id_to_guest_scan

Revision ID: 0223d60efc5c
Revises: da7da9bca5d7
Create Date: 2026-05-29 21:39:45.800899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0223d60efc5c'
down_revision: Union[str, Sequence[str], None] = 'da7da9bca5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.add_column('guest_scan_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('guest_scan_logs', 'ip_address',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_guest_scan_logs_user_id'), 'guest_scan_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'guest_scan_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guest_scan_logs', type_='foreignkey')
    op.drop_index(op.f('ix_guest_scan_logs_user_id'), table_name='guest_scan_logs')
    op.alter_column('guest_scan_logs', 'ip_address',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('guest_scan_logs', 'user_id')
    op.create_table('system_settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('maintenance_mode', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('allow_new_registrations', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('contact_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###
