"""add_template_settings

Revision ID: 2c817b7b8f35
Revises: 3b7dfc728972
Create Date: 2026-05-28 21:53:34.697298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c817b7b8f35'
down_revision: Union[str, Sequence[str], None] = '3b7dfc728972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('required_tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_settings_id'), 'template_settings', ['id'], unique=False)
    op.create_index(op.f('ix_template_settings_template_id'), 'template_settings', ['template_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_settings_template_id'), table_name='template_settings')
    op.drop_index(op.f('ix_template_settings_id'), table_name='template_settings')
    op.drop_table('template_settings')
    # ### end Alembic commands ###
