"""Add blog and media models

Revision ID: 61cf6ec47daa
Revises: 7680b792d0be
Create Date: 2026-05-31 20:26:14.548177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '61cf6ec47daa'
down_revision: Union[str, Sequence[str], None] = '7680b792d0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('content_blocks', sa.JSON(), nullable=False))
    op.add_column('blog_posts', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SCHEDULED', 'ARCHIVED', name='poststatus'), nullable=False))
    op.add_column('blog_posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('blog_posts', sa.Column('seo_description', sa.Text(), nullable=True))
    op.add_column('blog_posts', sa.Column('seo_keywords', sa.String(length=500), nullable=True))
    op.add_column('blog_posts', sa.Column('canonical_url', sa.String(length=500), nullable=True))
    op.add_column('blog_posts', sa.Column('focus_keyword', sa.String(length=255), nullable=True))
    op.add_column('blog_posts', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('blog_posts', sa.Column('is_sticky', sa.Boolean(), nullable=True))
    op.add_column('blog_posts', sa.Column('views_count', sa.Integer(), nullable=True))
    op.alter_column('blog_posts', 'excerpt',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_blog_posts_category'), table_name='blog_posts')
    op.drop_constraint(op.f('blog_posts_ibfk_1'), 'blog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'blog_posts', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'blog_posts', 'blog_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('blog_posts', 'category')
    op.drop_column('blog_posts', 'meta_keywords')
    op.drop_column('blog_posts', 'is_published')
    op.drop_column('blog_posts', 'tags')
    op.drop_column('blog_posts', 'meta_description')
    op.drop_column('blog_posts', 'og_image')
    op.drop_column('blog_posts', 'content')
    op.drop_column('blog_posts', 'schema_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('schema_data', mysql.JSON(), nullable=True))
    op.add_column('blog_posts', sa.Column('content', mysql.TEXT(), nullable=False))
    op.add_column('blog_posts', sa.Column('og_image', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('blog_posts', sa.Column('meta_description', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('blog_posts', sa.Column('tags', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('blog_posts', sa.Column('is_published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('blog_posts', sa.Column('meta_keywords', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('blog_posts', sa.Column('category', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.create_foreign_key(op.f('blog_posts_ibfk_1'), 'blog_posts', 'users', ['author_id'], ['id'])
    op.create_index(op.f('ix_blog_posts_category'), 'blog_posts', ['category'], unique=False)
    op.alter_column('blog_posts', 'excerpt',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('blog_posts', 'views_count')
    op.drop_column('blog_posts', 'is_sticky')
    op.drop_column('blog_posts', 'is_featured')
    op.drop_column('blog_posts', 'focus_keyword')
    op.drop_column('blog_posts', 'canonical_url')
    op.drop_column('blog_posts', 'seo_keywords')
    op.drop_column('blog_posts', 'seo_description')
    op.drop_column('blog_posts', 'category_id')
    op.drop_column('blog_posts', 'status')
    op.drop_column('blog_posts', 'content_blocks')
    # ### end Alembic commands ###
