"""add_user_id_to_guest_scan_logs

Revision ID: 7680b792d0be
Revises: 2516a3b56344
Create Date: 2026-05-29 21:45:05.930111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7680b792d0be'
down_revision: Union[str, Sequence[str], None] = '2516a3b56344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
