"""Add regional_prices to Plan

Revision ID: 7fb0ed768348
Revises: 87f2e74a53ae
Create Date: 2026-05-27 19:31:25.514420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb0ed768348'
down_revision: Union[str, Sequence[str], None] = '87f2e74a53ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('regional_prices', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'regional_prices')
    # ### end Alembic commands ###
