"""Add user tracking fields

Revision ID: 8637ce934e7a
Revises: a607b3516400
Create Date: 2026-05-26 22:48:39.341199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8637ce934e7a'
down_revision: Union[str, Sequence[str], None] = 'a607b3516400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_source', sa.Enum('EMAIL', 'GOOGLE', 'LINKEDIN', 'GITHUB', name='registrationsource'), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_password_reset', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_reset')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'registration_source')
    # ### end Alembic commands ###
