"""add_coupon_code_to_transactions

Revision ID: 9da577bce5af
Revises: d2e046b22a06
Create Date: 2026-05-29 17:01:31.692649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da577bce5af'
down_revision: Union[str, Sequence[str], None] = 'd2e046b22a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('coupon_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'coupon_code')
    # ### end Alembic commands ###
