"""Expand system settings

Revision ID: b9b773254747
Revises: d722ebfb0562
Create Date: 2026-06-01 14:25:33.372977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b773254747'
down_revision: Union[str, Sequence[str], None] = 'd722ebfb0562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('site_domain', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('site_logo', sa.String(length=500), nullable=True))
    op.add_column('system_settings', sa.Column('site_icon', sa.String(length=500), nullable=True))
    op.add_column('system_settings', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('system_settings', sa.Column('contact_address', sa.Text(), nullable=True))
    op.add_column('system_settings', sa.Column('social_links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'social_links')
    op.drop_column('system_settings', 'contact_address')
    op.drop_column('system_settings', 'contact_phone')
    op.drop_column('system_settings', 'site_icon')
    op.drop_column('system_settings', 'site_logo')
    op.drop_column('system_settings', 'site_domain')
    # ### end Alembic commands ###
