"""add_activity_and_guest_logs

Revision ID: cda1bea6141e
Revises: 2c817b7b8f35
Create Date: 2026-05-29 12:38:11.257371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda1bea6141e'
down_revision: Union[str, Sequence[str], None] = '2c817b7b8f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_scan_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_scan_logs_id'), 'guest_scan_logs', ['id'], unique=False)
    op.create_index(op.f('ix_guest_scan_logs_ip_address'), 'guest_scan_logs', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_scan_logs_ip_address'), table_name='guest_scan_logs')
    op.drop_index(op.f('ix_guest_scan_logs_id'), table_name='guest_scan_logs')
    op.drop_table('guest_scan_logs')
    # ### end Alembic commands ###
