"""Add visibility management tables

Revision ID: d08f233bb8b6
Revises: b9b773254747
Create Date: 2026-06-03 00:53:45.880697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08f233bb8b6'
down_revision: Union[str, Sequence[str], None] = 'b9b773254747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('perf_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_audits_id'), 'site_audits', ['id'], unique=False)
    op.create_table('visibility_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_info', sa.JSON(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('google_settings', sa.JSON(), nullable=True),
    sa.Column('ai_discovery', sa.JSON(), nullable=True),
    sa.Column('trust_center', sa.JSON(), nullable=True),
    sa.Column('branding_settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_configs_id'), 'visibility_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visibility_configs_id'), table_name='visibility_configs')
    op.drop_table('visibility_configs')
    op.drop_index(op.f('ix_site_audits_id'), table_name='site_audits')
    op.drop_table('site_audits')
    # ### end Alembic commands ###
