"""Add SEO management system

Revision ID: d722ebfb0562
Revises: 61cf6ec47daa
Create Date: 2026-06-01 11:40:50.520356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd722ebfb0562'
down_revision: Union[str, Sequence[str], None] = '61cf6ec47daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('is_followed', sa.Boolean(), nullable=True),
    sa.Column('og_title', sa.String(length=255), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image', sa.String(length=500), nullable=True),
    sa.Column('twitter_card', sa.String(length=50), nullable=True),
    sa.Column('faqs', sa.JSON(), nullable=True),
    sa.Column('custom_schema', sa.JSON(), nullable=True),
    sa.Column('include_in_sitemap', sa.Boolean(), nullable=True),
    sa.Column('sitemap_priority', sa.String(length=10), nullable=True),
    sa.Column('sitemap_changefreq', sa.String(length=20), nullable=True),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_configs_id'), 'seo_configs', ['id'], unique=False)
    op.create_index(op.f('ix_seo_configs_path'), 'seo_configs', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_configs_path'), table_name='seo_configs')
    op.drop_index(op.f('ix_seo_configs_id'), table_name='seo_configs')
    op.drop_table('seo_configs')
    # ### end Alembic commands ###
