"""enhance_coupon_logic

Revision ID: da7da9bca5d7
Revises: 9da577bce5af
Create Date: 2026-05-29 17:32:05.015763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da7da9bca5d7'
down_revision: Union[str, Sequence[str], None] = '9da577bce5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_coupon_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_coupon_usage_coupon_id'), 'user_coupon_usage', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_user_coupon_usage_id'), 'user_coupon_usage', ['id'], unique=False)
    op.create_index(op.f('ix_user_coupon_usage_user_id'), 'user_coupon_usage', ['user_id'], unique=False)
    op.add_column('coupons', sa.Column('max_uses_total', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('used_count_total', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('per_user_limit', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('min_purchase_amount', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('restricted_to_plan', sa.String(length=50), nullable=True))
    op.drop_column('coupons', 'max_uses')
    op.drop_column('coupons', 'used_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('used_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coupons', sa.Column('max_uses', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('coupons', 'restricted_to_plan')
    op.drop_column('coupons', 'min_purchase_amount')
    op.drop_column('coupons', 'per_user_limit')
    op.drop_column('coupons', 'used_count_total')
    op.drop_column('coupons', 'max_uses_total')
    op.drop_index(op.f('ix_user_coupon_usage_user_id'), table_name='user_coupon_usage')
    op.drop_index(op.f('ix_user_coupon_usage_id'), table_name='user_coupon_usage')
    op.drop_index(op.f('ix_user_coupon_usage_coupon_id'), table_name='user_coupon_usage')
    op.drop_table('user_coupon_usage')
    # ### end Alembic commands ###
